receivers:
  otlp:
    protocols:
        grpc:
          endpoint: localhost:4317
        http:
          endpoint: localhost:4318

exporters:
  debug:
    verbosity: normal

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]

